apiVersion: v1
items:
  - apiVersion: v1
    imagePullSecrets:
      - name: builder-dockercfg-hb5pb
    kind: ServiceAccount
    metadata:
      annotations:
        openshift.io/internal-registry-pull-secret-ref: builder-dockercfg-hb5pb
      name: builder
      namespace: humanresourceapps
    secrets:
      - name: builder-dockercfg-hb5pb
  - apiVersion: v1
    imagePullSecrets:
      - name: default-dockercfg-pzvlm
    kind: ServiceAccount
    metadata:
      annotations:
        openshift.io/internal-registry-pull-secret-ref: default-dockercfg-pzvlm
      name: default
      namespace: humanresourceapps
    secrets:
      - name: default-dockercfg-pzvlm
  - apiVersion: v1
    imagePullSecrets:
      - name: deployer-dockercfg-94ndp
    kind: ServiceAccount
    metadata:
      annotations:
        openshift.io/internal-registry-pull-secret-ref: deployer-dockercfg-94ndp
      name: deployer
      namespace: humanresourceapps
    secrets:
      - name: deployer-dockercfg-94ndp
  - apiVersion: v1
    imagePullSecrets:
      - name: useroot-dockercfg-clkbc
    kind: ServiceAccount
    metadata:
      annotations:
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"humanresourceapps-prd","app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"humanresourceapps","app.kubernetes.io/part-of":"humanresource-platform","environment":"production"},"name":"useroot","namespace":"humanresourceapps"}}
        openshift.io/internal-registry-pull-secret-ref: useroot-dockercfg-clkbc
      labels:
        app.kubernetes.io/instance: humanresourceapps-prd
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/name: humanresourceapps
        app.kubernetes.io/part-of: humanresource-platform
        environment: production
      name: useroot
      namespace: humanresourceapps
    secrets:
      - name: useroot-dockercfg-clkbc
kind: List
metadata:
  resourceVersion: ""
