apiVersion: v1
items:
  - apiVersion: v1
    imagePullSecrets:
      - name: builder-dockercfg-zqwr2
      - name: builder-quay-openshiftocp4
    kind: ServiceAccount
    metadata:
      name: builder
      namespace: humanresourceapps
    secrets:
      - name: builder-token-fcq9b
      - name: builder-dockercfg-zqwr2
      - name: builder-quay-openshiftocp4
  - apiVersion: v1
    imagePullSecrets:
      - name: default-dockercfg-n2nvt
      - name: kohlercitregistry
      - name: default-quay-openshiftocp4
    kind: ServiceAccount
    metadata:
      name: default
      namespace: humanresourceapps
    secrets:
      - name: default-token-hvrnk
      - name: default-dockercfg-n2nvt
      - name: default-quay-openshiftocp4
  - apiVersion: v1
    imagePullSecrets:
      - name: deployer-dockercfg-r7hzl
      - name: deployer-quay-openshiftocp4
    kind: ServiceAccount
    metadata:
      name: deployer
      namespace: humanresourceapps
    secrets:
      - name: deployer-token-q6vqw
      - name: deployer-dockercfg-r7hzl
      - name: deployer-quay-openshiftocp4
  - apiVersion: v1
    imagePullSecrets:
      - name: pipeline-dockercfg-gk72p
    kind: ServiceAccount
    metadata:
      name: pipeline
      namespace: humanresourceapps
      ownerReferences:
        - apiVersion: operator.tekton.dev/v1alpha1
          blockOwnerDeletion: true
          controller: true
          kind: TektonInstallerSet
          name: rhosp-rbac-rtd8g
          uid: 96a8678d-2bd8-40db-b38a-3df25a2060bc
    secrets:
      - name: pipeline-token-w6qss
      - name: pipeline-dockercfg-gk72p
  - apiVersion: v1
    imagePullSecrets:
      - name: useroot-dockercfg-96vwq
      - name: kohlercitregistry
    kind: ServiceAccount
    metadata:
      name: useroot
      namespace: humanresourceapps
    secrets:
      - name: useroot-dockercfg-96vwq
      - name: useroot-token-8wddn
kind: List
metadata:
  resourceVersion: ""
