apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: humanresourceapps-dev

namespace: humanresourceapps

resources:
  - ../../base

commonLabels:
  environment: development
  app.kubernetes.io/instance: humanresourceapps-dev

replicas:
  - name: "*"
    count: 1

images: []
