apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/azure-file
    creationTimestamp: "2022-09-20T13:00:36Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: mulesoft-accelerator
    namespace: mulesoftapps-prod
    resourceVersion: "301235631"
    uid: 54110b71-8559-411d-911d-31263eef7b38
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 10Gi
    storageClassName: azure-file
    volumeMode: Filesystem
    volumeName: pvc-54110b71-8559-411d-911d-31263eef7b38
  status:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 10Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/azure-file
    creationTimestamp: "2023-01-25T01:26:18Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: notifications-storage1
    namespace: mulesoftapps-prod
    resourceVersion: "963761546"
    uid: 06456964-148d-4417-8265-9e53dc2c4ec8
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 512Mi
    storageClassName: azure-file
    volumeMode: Filesystem
    volumeName: pvc-06456964-148d-4417-8265-9e53dc2c4ec8
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
