apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2022-09-20T13:09:06Z"
    labels:
      app: mulesoft-accelerator-2
    name: mulesoft-accelerator-2
    namespace: mulesoftapps-prod
    resourceVersion: "570304446"
    uid: 51f31960-9206-40b1-8e4a-9bf6b0d5e329
  spec:
    clusterIP: 172.30.244.181
    clusterIPs:
    - 172.30.244.181
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: 5001-tcp
      port: 5001
      protocol: TCP
      targetPort: 5001
    selector:
      app: mulesoft-accelerator-2
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
