apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-data-analytics-admin
rules:
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["create", "update", "patch", "delete", "get", "list", "watch"]
- apiGroups: ["security.openshift.io"]
  resources: ["securitycontextconstraints"]
  verbs: ["create", "update", "patch", "delete", "get", "list", "watch", "use"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["create", "update", "patch", "delete", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-data-analytics-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-data-analytics-admin
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
