apiVersion: v1
kind: Secret
metadata:
  name: kohler-apps-repo
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/rich-p-ai/kohler-apps.git
  # For public repositories, no credentials needed
  # For private repositories, add:
  # username: <your-username>
  # password: <your-token>
