apiVersion: v1
kind: Secret
metadata:
  name: kohler-apps-repo
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    managed-by: argocd.argoproj.io
type: Opaque
stringData:
  type: git
  url: https://github.com/rich-p-ai/kohler-apps.git
  name: kohler-apps
