apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-analytics-prd
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: data-analytics
    app.kubernetes.io/part-of: data-analytics-platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/rich-p-ai/koihler-apps.git
    targetRevision: HEAD
    path: data-analytics-migration/gitops/overlays/prd
  
  destination:
    server: https://kubernetes.default.svc
    namespace: data-analytics
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10
