apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: data-analytics-base
  annotations:
    argocd.argoproj.io/sync-wave: "1"

namespace: data-analytics

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - scc-binding.yaml

commonLabels:
  app.kubernetes.io/name: data-analytics
  app.kubernetes.io/part-of: data-analytics-platform
  app.kubernetes.io/managed-by: kustomize

patchesStrategicMerge: []
patchesJson6902: []
