apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: data-analytics-anyuid
  annotations:
    kubernetes.io/description: Custom SCC for data-analytics applications requiring anyuid
users:
- system:serviceaccount:data-analytics:useroot
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: null
defaultAddCapabilities: null
defaultPrivilegeEscalation: true
forbiddenSysctls:
- "*"
fsGroup:
  type: RunAsAny
groups: []
priority: 10
readOnlyRootFilesystem: false
requiredDropCapabilities:
- MKNOD
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
