apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/backup-registry-hostname: docker-registry.default.svc:5000
    openshift.io/backup-server-version: "1.11"
    openshift.io/description: Procurement Apps - > Application Programming
    openshift.io/display-name: Procurement Apps
    openshift.io/migration-registry: 172.30.151.208:5000
    openshift.io/requester: admin
    openshift.io/sa.scc.mcs: s0:c10,c0
    openshift.io/sa.scc.supplemental-groups: 1000090000/10000
    openshift.io/sa.scc.uid-range: 1000090000/10000
    operator.tekton.dev/prune.hash: e12cf88878007ab90299fa28c92d42daf72a1dda6ff604ea40c1f1da0f1f5e1d
  finalizers:
    - quay.redhat.com/quayintegrations
  labels:
    kubernetes.io/metadata.name: procurementapps
    openshift-pipelines.tekton.dev/namespace-reconcile-version: v1.6.4
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: v1.24
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: v1.24
  name: procurementapps
spec:
  finalizers:
    - kubernetes
