apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: humanresourceapps-base
  annotations:
    argocd.argoproj.io/sync-wave: "1"

namespace: humanresourceapps

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - scc-binding.yaml
  - rbac.yaml

commonLabels:
  app.kubernetes.io/name: humanresourceapps
  app.kubernetes.io/part-of: humanresource-platform
  app.kubernetes.io/managed-by: kustomize

patchesStrategicMerge: []
patchesJson6902: []
