apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: procurementapps-admins-binding
  namespace: procurementapps
  labels:
    app.kubernetes.io/name: procurementapps
    app.kubernetes.io/component: rbac
    app.kubernetes.io/managed-by: kustomize
subjects:
  - kind: Group
    name: procurementapps-admins
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
