apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: procurementapps-base

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - scc-binding.yaml
  - group.yaml
  - group-rolebinding.yaml

labels:
  - pairs:
      app.kubernetes.io/name: procurementapps
      app.kubernetes.io/part-of: kohler-apps
