apiVersion: v1
kind: ServiceAccount
metadata:
  name: useroot
  namespace: procurementapps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: useroot-anyuid
  namespace: procurementapps
subjects:
- kind: ServiceAccount
  name: useroot
  namespace: procurementapps
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:anyuid
  apiGroup: rbac.authorization.k8s.io
