apiVersion: batch/v1
kind: Job
metadata:
  name: export-nfspvcdataanalyticsdata01
  namespace: data-analytics
  labels:
    migration: data-analytics
    pvc: nfspvcdataanalyticsdata01
spec:
  template:
    metadata:
      labels:
        migration: data-analytics
        pvc: nfspvcdataanalyticsdata01
    spec:
      restartPolicy: Never
      serviceAccountName: useroot
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
      - name: export
        image: registry.redhat.io/ubi8/ubi:latest
        command:
        - /bin/bash
        - -c
        - |
          echo "Starting export of PVC: nfspvcdataanalyticsdata01"
          
          # Install required tools
          dnf install -y tar gzip
          
          # Check if source directory has data
          if [ -d "/source" ] && [ "$(find /source -mindepth 1 -maxdepth 1 | wc -l)" -gt 0 ]; then
            echo "Data found in /source, creating archive..."
            cd /source
            tar -czf "/backup/nfspvcdataanalyticsdata01-data.tar.gz" .
            echo "Archive created: nfspvcdataanalyticsdata01-data.tar.gz"
            echo "Archive size: $(du -h /backup/nfspvcdataanalyticsdata01-data.tar.gz)"
          else
            echo "No data found in /source for nfspvcdataanalyticsdata01"
            touch "/backup/nfspvcdataanalyticsdata01-empty.marker"
          fi
          
          echo "Export completed for PVC: nfspvcdataanalyticsdata01"
        volumeMounts:
        - name: source-data
          mountPath: /source
        - name: backup-storage
          mountPath: /backup
      volumes:
      - name: source-data
        persistentVolumeClaim:
          claimName: nfspvcdataanalyticsdata01
      - name: backup-storage
        persistentVolumeClaim:
          claimName: migration-backup-storage
---
