apiVersion: batch/v1
kind: Job
metadata:
  name: import-sftp-datalake-data01
  namespace: data-analytics
  labels:
    migration: data-analytics
    pvc: sftp-datalake-data01
spec:
  template:
    metadata:
      labels:
        migration: data-analytics
        pvc: sftp-datalake-data01
    spec:
      restartPolicy: Never
      serviceAccountName: useroot
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
      - name: import
        image: registry.redhat.io/ubi8/ubi:latest
        command:
        - /bin/bash
        - -c
        - |
          echo "Starting import for PVC: sftp-datalake-data01"
          
          # Install required tools
          dnf install -y tar gzip
          
          # Check for data archive
          if [ -f "/backup/sftp-datalake-data01-data.tar.gz" ]; then
            echo "Found data archive, extracting..."
            cd /target
            tar -xzf "/backup/sftp-datalake-data01-data.tar.gz"
            echo "Data extracted to /target"
          elif [ -f "/backup/sftp-datalake-data01-empty.marker" ]; then
            echo "PVC sftp-datalake-data01 was empty, no data to restore"
          else
            echo "No backup file found for sftp-datalake-data01"
          fi
          
          echo "Import completed for PVC: sftp-datalake-data01"
        volumeMounts:
        - name: target-data
          mountPath: /target
        - name: backup-storage
          mountPath: /backup
      volumes:
      - name: target-data
        persistentVolumeClaim:
          claimName: sftp-datalake-data01
      - name: backup-storage
        persistentVolumeClaim:
          claimName: migration-backup-storage
---
