apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: migration-backup-storage
  namespace: data-analytics
  labels:
    migration: data-analytics
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ocs-storagecluster-cephfs
---
