apiVersion: v1
kind: Namespace
metadata:
  name: data-analytics
  labels:
    name: data-analytics
    openshift.io/cluster-monitoring: "true"
    app.kubernetes.io/name: data-analytics
    app.kubernetes.io/part-of: data-analytics-platform
  annotations:
    openshift.io/description: "Data Analytics applications and services"
    openshift.io/display-name: "Data Analytics"
