apiVersion: v1
items:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      generation: 4
      name: dv15seei-batch
      namespace: humanresourceapps
    spec:
      lookupPolicy:
        local: false
      tags:
        - annotations: null
          from:
            kind: ImageStreamImage
            name: dv15seei-batch@sha256:2f5443b6790b2eb027e657e0539d520e3734e4543f91232ed8a1f3517fe86143
            namespace: programmingdevops
          generation: 3
          importPolicy:
            importMode: Legacy
          name: 2025.04.30
          referencePolicy:
            type: Source
        - annotations: null
          from:
            kind: ImageStreamImage
            name: dv15seei-batch@sha256:2f5443b6790b2eb027e657e0539d520e3734e4543f91232ed8a1f3517fe86143
            namespace: humanresourceapps
          generation: 4
          importPolicy:
            importMode: Legacy
          name: latest
          referencePolicy:
            type: Source
        - annotations: null
          from:
            kind: ImageStreamImage
            name: dv15seei-batch@sha256:2f5443b6790b2eb027e657e0539d520e3734e4543f91232ed8a1f3517fe86143
            namespace: programmingdevops
          generation: 2
          importPolicy:
            importMode: Legacy
          name: test
          referencePolicy:
            type: Source
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/image.dockerRepositoryCheck: "2025-07-16T19:34:20Z"
      generation: 14
      labels:
        app: hr01hrqp-batch
      name: hr01hrqp-batch
      namespace: humanresourceapps
    spec:
      lookupPolicy:
        local: true
      tags:
        - annotations: null
          from:
            kind: DockerImage
            name: kohlercitregistry.azurecr.io/hr01hrqp-batch:latest
          generation: 14
          importPolicy:
            importMode: Legacy
            scheduled: true
          name: latest
          referencePolicy:
            type: Source
        - annotations: null
          from:
            kind: DockerImage
            name: kohlercitregistry.azurecr.io/hr01hrqp-batch:test
          generation: 14
          importPolicy:
            importMode: Legacy
            scheduled: true
          name: test
          referencePolicy:
            type: Source
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/image.dockerRepositoryCheck: "2025-07-07T06:43:14Z"
      generation: 2
      labels:
        app: hr06esst-jco-prd
        app.kubernetes.io/component: hr06esst-jco-prd
        app.kubernetes.io/instance: hr06esst-jco-prd
        app.kubernetes.io/name: hr06esst-jco-prd
      name: hr06esst-jco-prd
      namespace: humanresourceapps
    spec:
      lookupPolicy:
        local: false
      tags:
        - annotations:
            openshift.io/generated-by: OpenShiftWebConsole
            openshift.io/imported-from: kohlercitregistry.azurecr.io/hr06esst_jco:latest
          from:
            kind: DockerImage
            name: kohlercitregistry.azurecr.io/hr06esst_jco:latest
          generation: 2
          importPolicy:
            importMode: Legacy
          name: latest
          referencePolicy:
            type: Local
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/image.dockerRepositoryCheck: "2025-07-07T06:16:18Z"
      generation: 2
      labels:
        app: hr06esst-jco-qa
        app.kubernetes.io/component: hr06esst-jco-qa
        app.kubernetes.io/instance: hr06esst-jco-qa
        app.kubernetes.io/name: hr06esst-jco-qa
      name: hr06esst-jco-qa
      namespace: humanresourceapps
    spec:
      lookupPolicy:
        local: false
      tags:
        - annotations:
            openshift.io/generated-by: OpenShiftWebConsole
            openshift.io/imported-from: kohlercitregistry.azurecr.io/hr06esst_jco:latest
          from:
            kind: DockerImage
            name: kohlercitregistry.azurecr.io/hr06esst_jco:latest
          generation: 2
          importPolicy:
            importMode: Legacy
          name: latest
          referencePolicy:
            type: Local
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/image.dockerRepositoryCheck: "2025-07-14T13:49:20Z"
      generation: 16
      labels:
        app: hr06esst_jco
      name: hr06esst_jco
      namespace: humanresourceapps
    spec:
      lookupPolicy:
        local: true
      tags:
        - annotations:
            openshift.io/generated-by: OpenShiftWebConsole
            openshift.io/imported-from: kohlercitregistry.azurecr.io/hr06esst_jco:latest
          from:
            kind: DockerImage
            name: kohlercitregistry.azurecr.io/hr06esst_jco:latest
          generation: 16
          importPolicy:
            importMode: Legacy
            scheduled: true
          name: latest
          referencePolicy:
            type: Source
        - annotations:
            openshift.io/generated-by: OpenShiftWebConsole
            openshift.io/imported-from: kohlercitregistry.azurecr.io/hr06esst_jco:test
          from:
            kind: DockerImage
            name: kohlercitregistry.azurecr.io/hr06esst_jco:test
          generation: 16
          importPolicy:
            importMode: Legacy
            scheduled: true
          name: test
          referencePolicy:
            type: Source
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      generation: 2
      name: mulesoft-bulk-dev
      namespace: humanresourceapps
    spec:
      lookupPolicy:
        local: false
      tags:
        - annotations: null
          from:
            kind: ImageStreamImage
            name: mulesoft-bulk@sha256:1cd36fdf70b6e6c475ebc0c956863ee2fc4fc4e2272bfe9a64d3277dab32bcba
            namespace: programmingdevops
          generation: 2
          importPolicy:
            importMode: Legacy
          name: latest
          referencePolicy:
            type: Source
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      generation: 3
      name: mulesoft-bulk-prd
      namespace: humanresourceapps
    spec:
      lookupPolicy:
        local: false
      tags:
        - annotations: null
          from:
            kind: ImageStreamImage
            name: mulesoft-bulk-qa@sha256:262c66ef48b6c4a83024788f6ee688be135a7d1edc84ed769c2724a63edd1d24
            namespace: humanresourceapps
          generation: 3
          importPolicy:
            importMode: Legacy
          name: 2024.04.16
          referencePolicy:
            type: Source
        - annotations: null
          from:
            kind: ImageStreamImage
            name: mulesoft-bulk-qa@sha256:262c66ef48b6c4a83024788f6ee688be135a7d1edc84ed769c2724a63edd1d24
            namespace: humanresourceapps
          generation: 2
          importPolicy:
            importMode: Legacy
          name: latest
          referencePolicy:
            type: Source
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      generation: 3
      name: mulesoft-bulk-qa
      namespace: humanresourceapps
    spec:
      lookupPolicy:
        local: false
      tags:
        - annotations: null
          from:
            kind: ImageStreamImage
            name: mulesoft-bulk@sha256:262c66ef48b6c4a83024788f6ee688be135a7d1edc84ed769c2724a63edd1d24
            namespace: programmingdevops
          generation: 3
          importPolicy:
            importMode: Legacy
          name: 2024.04.16
          referencePolicy:
            type: Source
        - annotations: null
          from:
            kind: ImageStreamImage
            name: mulesoft-bulk@sha256:262c66ef48b6c4a83024788f6ee688be135a7d1edc84ed769c2724a63edd1d24
            namespace: programmingdevops
          generation: 2
          importPolicy:
            importMode: Legacy
          name: latest
          referencePolicy:
            type: Source
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      generation: 7
      name: user-services-imports
      namespace: humanresourceapps
    spec:
      lookupPolicy:
        local: false
      tags:
        - annotations: null
          from:
            kind: ImageStreamImage
            name: user-services-imports@sha256:f1748cb76b0ac4e69b2211838fb4cc6789e5a5c45c0238871e3962af61a2ef0b
            namespace: programmingdevops
          generation: 6
          importPolicy:
            importMode: Legacy
          name: 2025.03.11
          referencePolicy:
            type: Source
        - annotations: null
          from:
            kind: ImageStreamImage
            name: user-services-imports@sha256:f1748cb76b0ac4e69b2211838fb4cc6789e5a5c45c0238871e3962af61a2ef0b
            namespace: humanresourceapps
          generation: 7
          importPolicy:
            importMode: Legacy
          name: latest
          referencePolicy:
            type: Source
        - annotations: null
          from:
            kind: ImageStreamImage
            name: user-services-imports@sha256:f1748cb76b0ac4e69b2211838fb4cc6789e5a5c45c0238871e3962af61a2ef0b
            namespace: programmingdevops
          generation: 5
          importPolicy:
            importMode: Legacy
          name: test
          referencePolicy:
            type: Source
kind: List
metadata:
  resourceVersion: ""
