apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: humanresourceapps-prd

namespace: humanresourceapps

resources:
  - ../../base
  - configmaps-cleaned.yaml
  - deployments-cleaned.yaml
  - imagestreams-cleaned.yaml
  - pvcs-cleaned.yaml
  - routes-cleaned.yaml
  - secrets-cleaned.yaml
  - services-cleaned.yaml

commonLabels:
  environment: production
  app.kubernetes.io/instance: humanresourceapps-prd

images: []
