apiVersion: v1
items:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"route.openshift.io/v1","kind":"Route","metadata":{"annotations":{"openshift.io/host.generated":"true"},"labels":{"app":"couchdb-employee-prd","app.kubernetes.io/component":"couchdb-employee-prd","app.kubernetes.io/instance":"humanresourceapps-prd","app.kubernetes.io/part-of":"couchdb-employee","environment":"production"},"name":"couchdb-employee-prd","namespace":"humanresourceapps"},"spec":{"host":"couchdb-employee-prd-humanresourceapps.apps.ocp-prd.kohlerco.com","port":{"targetPort":"6984-tcp"},"tls":{"termination":"passthrough"},"to":{"kind":"Service","name":"couchdb-employee-prd","weight":100},"wildcardPolicy":"None"}}
      openshift.io/host.generated: "true"
    creationTimestamp: "2025-07-04T10:26:37Z"
    labels:
      app: couchdb-employee-prd
      app.kubernetes.io/component: couchdb-employee-prd
      app.kubernetes.io/instance: humanresourceapps-prd
      app.kubernetes.io/part-of: couchdb-employee
      environment: production
    name: couchdb-employee-prd
    namespace: humanresourceapps
    resourceVersion: "190587290"
    uid: b44c0aa1-d5d7-4357-bba0-8c57f68bc30e
  spec:
    host: couchdb-employee-prd-humanresourceapps.apps.ocp-prd.kohlerco.com
    port:
      targetPort: 6984-tcp
    tls:
      termination: passthrough
    to:
      kind: Service
      name: couchdb-employee-prd
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: "2025-07-04T10:26:37Z"
        status: "True"
        type: Admitted
      host: couchdb-employee-prd-humanresourceapps.apps.ocp-prd.kohlerco.com
      routerCanonicalHostname: router-default.apps.ocp-prd.kohlerco.com
      routerName: default
      wildcardPolicy: None
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"route.openshift.io/v1","kind":"Route","metadata":{"annotations":{"openshift.io/host.generated":"true"},"labels":{"app":"couchdb-employee-qa","app.kubernetes.io/component":"couchdb-employee-qa","app.kubernetes.io/instance":"humanresourceapps-prd","app.kubernetes.io/part-of":"couchdb-employee","environment":"production"},"name":"couchdb-employee-qa","namespace":"humanresourceapps"},"spec":{"host":"couchdb-employee-qa-humanresourceapps.apps.ocp-prd.kohlerco.com","port":{"targetPort":"6984-tcp"},"tls":{"termination":"passthrough"},"to":{"kind":"Service","name":"couchdb-employee-qa","weight":100},"wildcardPolicy":"None"}}
      openshift.io/host.generated: "true"
    creationTimestamp: "2025-07-04T10:20:23Z"
    labels:
      app: couchdb-employee-qa
      app.kubernetes.io/component: couchdb-employee-qa
      app.kubernetes.io/instance: humanresourceapps-prd
      app.kubernetes.io/part-of: couchdb-employee
      environment: production
    name: couchdb-employee-qa
    namespace: humanresourceapps
    resourceVersion: "190587292"
    uid: a7ea3278-a846-486a-a122-1d8f5d64a306
  spec:
    host: couchdb-employee-qa-humanresourceapps.apps.ocp-prd.kohlerco.com
    port:
      targetPort: 6984-tcp
    tls:
      termination: passthrough
    to:
      kind: Service
      name: couchdb-employee-qa
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: "2025-07-04T10:20:23Z"
        status: "True"
        type: Admitted
      host: couchdb-employee-qa-humanresourceapps.apps.ocp-prd.kohlerco.com
      routerCanonicalHostname: router-default.apps.ocp-prd.kohlerco.com
      routerName: default
      wildcardPolicy: None
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    creationTimestamp: "2025-07-09T14:13:48Z"
    labels:
      app: directvolumemigration-rsync-transfer
      app.kubernetes.io/part-of: openshift-migration
      directvolumemigration: d75bba62-0c6c-4855-8efc-bb230639d4c8
      migration.openshift.io/migrated-by-migplan: ba008ae5-0381-4e18-93c9-455b7486a653
      owner: directvolumemigration
      purpose: rsync
    name: dvm
    namespace: humanresourceapps
    resourceVersion: "176683197"
    uid: df1755ad-0dd6-483b-b962-a40b0c1549b0
  spec:
    host: dvm-humanresourceapps.apps.ocp-prd.kohlerco.com
    port:
      targetPort: 6443
    subdomain: apps.ocp-prd.kohlerco.com
    tls:
      termination: passthrough
    to:
      kind: Service
      name: dvm
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: "2025-07-09T14:13:48Z"
        status: "True"
        type: Admitted
      host: dvm-humanresourceapps.apps.ocp-prd.kohlerco.com
      routerCanonicalHostname: router-default.apps.ocp-prd.kohlerco.com
      routerName: default
      wildcardPolicy: None
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    creationTimestamp: "2025-07-09T14:13:48Z"
    labels:
      app: directvolumemigration-rsync-transfer-block
      app.kubernetes.io/part-of: openshift-migration
      directvolumemigration: d75bba62-0c6c-4855-8efc-bb230639d4c8
      migration.openshift.io/migrated-by-migplan: ba008ae5-0381-4e18-93c9-455b7486a653
      owner: directvolumemigration
      purpose: rsync
    name: dvm-block
    namespace: humanresourceapps
    resourceVersion: "176683203"
    uid: 1a1717e6-184f-439d-af60-e52879c4d21f
  spec:
    host: dvm-block-humanresourceapps.apps.ocp-prd.kohlerco.com
    port:
      targetPort: 6443
    subdomain: apps.ocp-prd.kohlerco.com
    tls:
      termination: passthrough
    to:
      kind: Service
      name: dvm-block
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: "2025-07-09T14:13:48Z"
        status: "True"
        type: Admitted
      host: dvm-block-humanresourceapps.apps.ocp-prd.kohlerco.com
      routerCanonicalHostname: router-default.apps.ocp-prd.kohlerco.com
      routerName: default
      wildcardPolicy: None
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
      openshift.io/host.generated: "true"
    creationTimestamp: "2025-07-07T06:43:15Z"
    labels:
      app: hr06esst-jco-prd
      app.kubernetes.io/component: hr06esst-jco-prd
      app.kubernetes.io/instance: hr06esst-jco-prd
      app.kubernetes.io/name: hr06esst-jco-prd
      app.openshift.io/runtime-version: latest
    name: hr06esst-jco-prd
    namespace: humanresourceapps
    resourceVersion: "174568987"
    uid: 7fc668e1-d3a7-402f-839b-7b8ba8d4654a
  spec:
    host: hr06esst-jco-prd.apps.ocp-prd.kohlerco.com
    port:
      targetPort: 8080-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: hr06esst-jco-prd
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: "2025-07-07T06:48:55Z"
        status: "True"
        type: Admitted
      host: hr06esst-jco-prd.apps.ocp-prd.kohlerco.com
      routerCanonicalHostname: router-default.apps.ocp-prd.kohlerco.com
      routerName: default
      wildcardPolicy: None
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
      openshift.io/host.generated: "true"
    creationTimestamp: "2025-07-07T06:16:19Z"
    labels:
      app: hr06esst-jco-qa
      app.kubernetes.io/component: hr06esst-jco-qa
      app.kubernetes.io/instance: hr06esst-jco-qa
      app.kubernetes.io/name: hr06esst-jco-qa
      app.openshift.io/runtime-version: latest
    name: hr06esst-jco-qa
    namespace: humanresourceapps
    resourceVersion: "174553084"
    uid: b55df9b4-6b78-4580-b66e-7c82acf99354
  spec:
    host: hr06esst-jco-qa.apps.ocp-prd.kohlerco.com
    port:
      targetPort: 8080-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: hr06esst-jco-qa
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: "2025-07-07T06:23:15Z"
        status: "True"
        type: Admitted
      host: hr06esst-jco-qa.apps.ocp-prd.kohlerco.com
      routerCanonicalHostname: router-default.apps.ocp-prd.kohlerco.com
      routerName: default
      wildcardPolicy: None
kind: List
metadata:
  resourceVersion: ""
