apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      app.openshift.io/vcs-ref: main
      app.openshift.io/vcs-uri: https://github.com/apache/couchdb-docker
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: "2022-05-18T17:38:38Z"
    labels:
      app: couchdb-employee-dev
      app.kubernetes.io/component: couchdb-employee-dev
      app.kubernetes.io/instance: couchdb-employee-dev
      app.kubernetes.io/part-of: couchdb-employee
    name: couchdb-employee-dev
    namespace: humanresourceapps
    resourceVersion: "745687273"
    uid: e9dbb85c-66ae-4085-8ac3-18a565a4b60d
  spec:
    clusterIP: 172.30.176.70
    clusterIPs:
    - 172.30.176.70
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: 4369-tcp
      port: 4369
      protocol: TCP
      targetPort: 4369
    - name: 5984-tcp
      port: 5984
      protocol: TCP
      targetPort: 5984
    - name: 6984-tcp
      port: 6984
      protocol: TCP
      targetPort: 6984
    - name: 9100-tcp
      port: 9100
      protocol: TCP
      targetPort: 9100
    selector:
      app: couchdb-employee-dev
      deploymentconfig: couchdb-employee-dev
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      app.openshift.io/vcs-ref: main
      app.openshift.io/vcs-uri: https://github.com/apache/couchdb-docker
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: "2022-05-19T20:12:31Z"
    labels:
      app: couchdb-employee-prd
      app.kubernetes.io/component: couchdb-employee-prd
      app.kubernetes.io/instance: couchdb-employee-prd
      app.kubernetes.io/part-of: couchdb-employee
    name: couchdb-employee-prd
    namespace: humanresourceapps
    resourceVersion: "746860455"
    uid: 5fff23bc-7cfd-482b-8892-441c2f18c76d
  spec:
    clusterIP: 172.30.18.67
    clusterIPs:
    - 172.30.18.67
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: 4369-tcp
      port: 4369
      protocol: TCP
      targetPort: 4369
    - name: 5984-tcp
      port: 5984
      protocol: TCP
      targetPort: 5984
    - name: 6984-tcp
      port: 6984
      protocol: TCP
      targetPort: 6984
    - name: 9100-tcp
      port: 9100
      protocol: TCP
      targetPort: 9100
    selector:
      app: couchdb-employee-prd
      deploymentconfig: couchdb-employee-prd
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      app.openshift.io/vcs-ref: main
      app.openshift.io/vcs-uri: https://github.com/apache/couchdb-docker
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: "2022-05-19T20:11:38Z"
    labels:
      app: couchdb-employee-qa
      app.kubernetes.io/component: couchdb-employee-qa
      app.kubernetes.io/instance: couchdb-employee-qa
      app.kubernetes.io/part-of: couchdb-employee
    name: couchdb-employee-qa
    namespace: humanresourceapps
    resourceVersion: "746859769"
    uid: f51b7861-b11d-4b2c-84fd-2779ea489d63
  spec:
    clusterIP: 172.30.79.115
    clusterIPs:
    - 172.30.79.115
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: 4369-tcp
      port: 4369
      protocol: TCP
      targetPort: 4369
    - name: 5984-tcp
      port: 5984
      protocol: TCP
      targetPort: 5984
    - name: 6984-tcp
      port: 6984
      protocol: TCP
      targetPort: 6984
    - name: 9100-tcp
      port: 9100
      protocol: TCP
      targetPort: 9100
    selector:
      app: couchdb-employee-qa
      deploymentconfig: couchdb-employee-qa
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: "2022-04-14T13:14:40Z"
    labels:
      app: hr06esst-jco-prd
      app.kubernetes.io/component: hr06esst-jco-prd
      app.kubernetes.io/instance: hr06esst-jco-prd
      app.kubernetes.io/part-of: hr06esst-jco
    name: hr06esst-jco-prd
    namespace: humanresourceapps
    resourceVersion: "707455086"
    uid: 9b06ee4b-6551-4d4b-9f2d-ace58df8f144
  spec:
    clusterIP: 172.30.17.55
    clusterIPs:
    - 172.30.17.55
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: hr06esst-jco-prd
      deploymentconfig: hr06esst-jco-prd
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: "2024-02-01T16:30:37Z"
    labels:
      app: hr06esst-jco-pwr-prd
      app.kubernetes.io/component: hr06esst-jco-pwr-prd
      app.kubernetes.io/instance: hr06esst-jco-pwr-prd
    name: hr06esst-jco-pwr-prd
    namespace: humanresourceapps
    resourceVersion: "5214874217"
    uid: 7055d033-c6a4-4489-b9b8-1661f558344a
  spec:
    clusterIP: 172.30.181.59
    clusterIPs:
    - 172.30.181.59
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: hr06esst-jco-pwr-prd
      deploymentconfig: hr06esst-jco-pwr-prd
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: "2024-01-29T20:29:40Z"
    labels:
      app: hr06esst-jco-pwr-qa
      app.kubernetes.io/component: hr06esst-jco-pwr-qa
      app.kubernetes.io/instance: hr06esst-jco-pwr-qa
      app.kubernetes.io/part-of: hr06esst-pwr-jco
    name: hr06esst-jco-pwr-qa
    namespace: humanresourceapps
    resourceVersion: "3179284057"
    uid: 4958f737-57a6-44ed-b9e0-b8135412be33
  spec:
    clusterIP: 172.30.182.85
    clusterIPs:
    - 172.30.182.85
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: hr06esst-jco-pwr-qa
      deploymentconfig: hr06esst-jco-pwr-qa
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: "2022-04-13T19:46:26Z"
    labels:
      app: hr06esst-jco-qa
      app.kubernetes.io/component: hr06esst-jco-qa
      app.kubernetes.io/instance: hr06esst-jco-qa
      app.kubernetes.io/part-of: hr06esst-jco
    name: hr06esst-jco-qa
    namespace: humanresourceapps
    resourceVersion: "706643658"
    uid: f451fc45-a4b6-4ca5-b50f-6aeaec761a31
  spec:
    clusterIP: 172.30.122.52
    clusterIPs:
    - 172.30.122.52
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: hr06esst-jco-qa
      deploymentconfig: hr06esst-jco-qa
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      app.openshift.io/vcs-ref: ""
      app.openshift.io/vcs-uri: https://github.com/sclorg/httpd-ex.git
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: "2022-05-05T11:24:16Z"
    labels:
      app: httpd-temp
      app.kubernetes.io/component: httpd-temp
      app.kubernetes.io/instance: httpd-temp
      app.kubernetes.io/name: httpd
      app.kubernetes.io/part-of: httpd-temp
      app.openshift.io/runtime: httpd
      app.openshift.io/runtime-version: 2.4-el7
    name: httpd-temp
    namespace: humanresourceapps
    resourceVersion: "730838400"
    uid: 8266a451-e420-40a9-989b-6293fe2ae361
  spec:
    clusterIP: 172.30.51.222
    clusterIPs:
    - 172.30.51.222
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      app: httpd-temp
      deploymentconfig: httpd-temp
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
