apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- serviceaccount.yaml
- scc-binding.yaml

labels:
- pairs:
    app.kubernetes.io/name: oraclecpq
    app.kubernetes.io/component: oracle-cpq
    app.kubernetes.io/managed-by: argocd
