apiVersion: v1
items:
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      annotations:
        openshift.io/host.generated: "true"
      labels:
        app: sftp-data-analytics-app1
        app.kubernetes.io/component: sftp-data-analytics-app1
        app.kubernetes.io/instance: sftp-data-analytics-app1
        app.kubernetes.io/part-of: sftp-data-analytics-app1
      name: sftp-data-analytics-app1
      namespace: data-analytics
    spec:
      host: sftp-data-analytics-app1-data-analytics.apps.ocp-prd.kohlerco.com
      port:
        targetPort: 22-tcp
      to:
        kind: Service
        name: sftp-data-analytics-app1
        weight: 100
      wildcardPolicy: None
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      annotations:
        openshift.io/host.generated: "true"
      labels:
        app: sftp-data-lake-app1
        app.kubernetes.io/component: sftp-data-lake-app1
        app.kubernetes.io/instance: sftp-data-lake-app1
        app.kubernetes.io/part-of: sftp-data-lake-app1
      name: sftp-data-lake-app1
      namespace: data-analytics
    spec:
      host: sftp-data-lake-app1-data-analytics.apps.ocp-prd.kohlerco.com
      port:
        targetPort: 22-tcp
      to:
        kind: Service
        name: sftp-data-lake-app1
        weight: 100
      wildcardPolicy: None
kind: List
metadata:
  resourceVersion: ""
