apiVersion: v1
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: pipeline
      namespace: data-analytics
      ownerReferences:
        - apiVersion: operator.tekton.dev/v1alpha1
          blockOwnerDeletion: true
          controller: true
          kind: TektonInstallerSet
          name: rhosp-rbac-rtd8g
          uid: 96a8678d-2bd8-40db-b38a-3df25a2060bc
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: useroot
      namespace: data-analytics
kind: List
metadata:
  resourceVersion: ""
