apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: data-analytics

bases:
  - ../../base

patchesJson6902:
  - target:
      group: ""
      version: v1
      kind: Namespace
      name: data-analytics
    patch: |-
      - op: add
        path: /metadata/labels/environment
        value: production
      - op: add
        path: /metadata/annotations/openshift.io~1display-name
        value: "Data Analytics - Production"

resources: []
# Will be populated after running migration script:
# - storage.yaml
# - secrets.yaml
# - configmaps.yaml
# - deployments.yaml
# - services.yaml
# - routes.yaml

replicas:
  - name: "*"
    count: 2

commonLabels:
  environment: production
  tier: production
