apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: data-analytics

resources:
  - ../../base

patches:
  - target:
      group: ""
      version: v1
      kind: Namespace
      name: data-analytics
    patch: |-
      - op: add
        path: /metadata/labels/environment
        value: production
      - op: add
        path: /metadata/annotations/openshift.io~1display-name
        value: "Data Analytics - Production"

labels:
  - pairs:
      environment: production
      tier: production
