apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        app.openshift.io/vcs-ref: sftp
        app.openshift.io/vcs-uri: https://bitbucket.org/kohler_prime/ia_unix
        openshift.io/generated-by: OpenShiftWebConsole
      labels:
        app: cdh-callfinder-sftp-app
        app.kubernetes.io/component: cdh-callfinder-sftp-app
        app.kubernetes.io/instance: cdh-callfinder-sftp-app
        app.kubernetes.io/name: cdh-callfinder-sftp-app
        app.kubernetes.io/part-of: cdh-callfinder
      name: cdh-callfinder-sftp-app
      namespace: data-analytics
    spec:
      externalTrafficPolicy: Cluster
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: 22-tcp
          nodePort: 32073
          port: 22
          protocol: TCP
          targetPort: 22
      selector:
        app: cdh-callfinder-sftp-app
        deploymentconfig: cdh-callfinder-sftp-app
      sessionAffinity: None
      type: NodePort
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        app.openshift.io/vcs-ref: sftp
        app.openshift.io/vcs-uri: https://bitbucket.org/kohler_prime/ia_unix.git
        openshift.io/generated-by: OpenShiftWebConsole
      labels:
        app: sci-scorecard-dev-stage1
        app.kubernetes.io/component: sci-scorecard-dev-stage1
        app.kubernetes.io/instance: sci-scorecard-dev-stage1
        app.kubernetes.io/name: sci-scorecard-dev-stage1
        app.kubernetes.io/part-of: sci-scorecard
      name: sci-scorecard-dev-stage1
      namespace: data-analytics
    spec:
      externalTrafficPolicy: Cluster
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: 22-tcp
          nodePort: 32105
          port: 22
          protocol: TCP
          targetPort: 22
      selector:
        app: sci-scorecard-dev-stage1
        deploymentconfig: sci-scorecard-dev-stage1
      sessionAffinity: None
      type: NodePort
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      labels:
        app: sftp-data-analytics-app1
        app.kubernetes.io/component: sftp-data-analytics-app1
        app.kubernetes.io/instance: sftp-data-analytics-app1
        app.kubernetes.io/part-of: sftp-data-analytics-app1
      name: sftp-data-analytics-app1
      namespace: data-analytics
    spec:
      externalTrafficPolicy: Cluster
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: 22-tcp
          nodePort: 32005
          port: 22
          protocol: TCP
          targetPort: 22
      selector:
        app: sftp-data-analytics-app1
        deploymentconfig: sftp-data-analytics-app1
      sessionAffinity: None
      type: NodePort
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        app.openshift.io/vcs-ref: sftp
        app.openshift.io/vcs-uri: https://bitbucket.org/kohler_prime/ia_unix
        openshift.io/generated-by: OpenShiftWebConsole
      labels:
        app: sftp-data-lake-app1
        app.kubernetes.io/component: sftp-data-lake-app1
        app.kubernetes.io/instance: sftp-data-lake-app1
        app.kubernetes.io/part-of: sftp-data-lake-app1
      name: sftp-data-lake-app1
      namespace: data-analytics
    spec:
      externalTrafficPolicy: Cluster
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: 22-tcp
          nodePort: 32010
          port: 22
          protocol: TCP
          targetPort: 22
      selector:
        app: sftp-data-lake-app1
        deploymentconfig: sftp-data-lake-app1
      sessionAffinity: None
      type: NodePort
kind: List
metadata:
  resourceVersion: ""
