apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - scc-binding.yaml

commonLabels:
  app.kubernetes.io/name: mulesoftapps
  app.kubernetes.io/part-of: mulesoftapps
  app.kubernetes.io/managed-by: argocd
  migrated-from: ocpaz
