apiVersion: v1
items:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
        volume.kubernetes.io/storage-provisioner: openshift-storage.cephfs.csi.ceph.com
      finalizers:
        - kubernetes.io/pvc-protection
      name: cdh-callfinder-vol01
      namespace: data-analytics
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 2Gi
      storageClassName: ocs-external-storagecluster-cephfs
      volumeMode: Filesystem
      volumeName: pvc-34097b5b-bff8-434b-93c5-f2124fbebb90
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations: {}
      finalizers:
        - kubernetes.io/pvc-protection
      labels:
        velero.io/exclude-from-backup: "true"
      name: nfspvcdataanalyticsdata01
      namespace: data-analytics
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 10Gi
      storageClassName: nfs
      volumeMode: Filesystem
      volumeName: nfspvdataanalyticsdata01
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
        volume.kubernetes.io/storage-provisioner: openshift-storage.cephfs.csi.ceph.com
      finalizers:
        - kubernetes.io/pvc-protection
      name: sci-scorecard-dev-vol01
      namespace: data-analytics
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 2Gi
      storageClassName: ocs-external-storagecluster-cephfs
      volumeMode: Filesystem
      volumeName: pvc-a6fe3c3f-9698-487c-8652-cc2e34bb99ba
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations: {}
      finalizers:
        - kubernetes.io/pvc-protection
      name: sftp-analytics-01
      namespace: data-analytics
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: thin
      volumeMode: Filesystem
      volumeName: pvc-31a78975-4210-4795-95c4-a364a1371e57
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations: {}
      finalizers:
        - kubernetes.io/pvc-protection
      labels:
        velero.io/exclude-from-backup: "true"
      name: sftp-analytics-data01
      namespace: data-analytics
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 10Gi
      storageClassName: isilon-storageclass
      volumeMode: Filesystem
      volumeName: csipscale-9d3f70bb02
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations: {}
      finalizers:
        - kubernetes.io/pvc-protection
      name: sftp-datalake-01
      namespace: data-analytics
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 1Gi
      storageClassName: ocs-external-storagecluster-cephfs
      volumeMode: Filesystem
      volumeName: pvc-19a9af7d-426d-4ba6-9fdf-65978d442731
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations: {}
      finalizers:
        - kubernetes.io/pvc-protection
      labels:
        velero.io/exclude-from-backup: "true"
      name: sftp-datalake-data01
      namespace: data-analytics
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 5Gi
      storageClassName: isilon-storageclass-v6
      volumeMode: Filesystem
      volumeName: csipscale-ca2b9e6e4d
kind: List
metadata:
  resourceVersion: ""
