apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oraclecpq

resources:
- ../../base
- configmaps.yaml
- cronjobs.yaml
- deployments.yaml
- jobs.yaml
- networkpolicies.yaml
- nfs-persistent-volumes.yaml
- pvcs.yaml
- rolebindings.yaml
- routes.yaml
- secrets.yaml
- serviceaccounts.yaml
- services.yaml
- statefulsets.yaml

images: []

labels:
- pairs:
    environment: production
    cluster: ocp-prd
