apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      alpha.image.policy.openshift.io/resolve-names: '*'
      app.openshift.io/route-disabled: "false"
      app.openshift.io/vcs-ref: sftp
      app.openshift.io/vcs-uri: https://bitbucket.org/kohler_prime/ia_unix
      deployment.kubernetes.io/revision: "9"
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"cdh-callfinder-sftp-app:latest","namespace":"data-analytics"},"fieldPath":"spec.template.spec.containers[?(@.name==\"cdh-callfinder-sftp-app\")].image","pause":"false"}]'
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: "2023-09-08T11:57:47Z"
    generation: 13
    labels:
      app: cdh-callfinder-sftp-app
      app.kubernetes.io/component: cdh-callfinder-sftp-app
      app.kubernetes.io/instance: cdh-callfinder-sftp-app
      app.kubernetes.io/name: cdh-callfinder-sftp-app
      app.kubernetes.io/part-of: cdh-callfinder
    name: cdh-callfinder-sftp-app
    namespace: data-analytics
    resourceVersion: "4513276406"
    uid: d5341c4f-13f4-4856-a687-2e87295d928a
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: cdh-callfinder-sftp-app
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: cdh-callfinder-sftp-app
          deploymentconfig: cdh-callfinder-sftp-app
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/data-analytics/cdh-callfinder-sftp-app@sha256:8ad8bf808e53c61c76cdde3546a4d352f52beaddb3bd622ce5713969a34f55b4
          imagePullPolicy: Always
          name: cdh-callfinder-sftp-app
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/sftp
            name: volume-sftp-users
            readOnly: true
          - mountPath: /home/cdh-users/.ssh/keys/
            name: volume-9lwmg
            readOnly: true
          - mountPath: /home/cdh-users
            name: cdh-callfinder-vol01
            subPath: home/
          - mountPath: /etc/ssh/ssh_host_ed25519_key
            name: cdh-callfinder-vol01
            readOnly: true
            subPath: keys/ssh_host_ed25519_key
          - mountPath: /etc/ssh/ssh_host_rsa_key
            name: cdh-callfinder-vol01
            readOnly: true
            subPath: keys/ssh_host_rsa_key
          - mountPath: /etc/ssh/ssh_host_ed25519_key.pub
            name: cdh-callfinder-vol01
            readOnly: true
            subPath: keys/ssh_host_ed25519_key.pub
          - mountPath: /etc/ssh/ssh_host_rsa_key.pub
            name: cdh-callfinder-vol01
            readOnly: true
            subPath: keys/ssh_host_rsa_key.pub
          - mountPath: /data
            name: cdh-callfinder-vol01
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: useroot
        serviceAccountName: useroot
        terminationGracePeriodSeconds: 30
        volumes:
        - name: cdh-callfinder-vol01
          persistentVolumeClaim:
            claimName: cdh-callfinder-vol01
        - configMap:
            defaultMode: 420
            name: cdh-users
          name: volume-sftp-users
        - configMap:
            defaultMode: 420
            name: cdh-users-ssh-pub
          name: volume-9lwmg
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2023-09-08T11:57:47Z"
      lastUpdateTime: "2023-09-08T12:22:44Z"
      message: ReplicaSet "cdh-callfinder-sftp-app-5b6db6d7dc" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2024-12-07T16:11:24Z"
      lastUpdateTime: "2024-12-07T16:11:24Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 13
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      alpha.image.policy.openshift.io/resolve-names: '*'
      app.openshift.io/route-disabled: "false"
      app.openshift.io/vcs-ref: sftp
      app.openshift.io/vcs-uri: https://bitbucket.org/kohler_prime/ia_unix.git
      deployment.kubernetes.io/revision: "18"
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"sci-scorecard-dev-stage1:latest","namespace":"data-analytics"},"fieldPath":"spec.template.spec.containers[?(@.name==\"sci-scorecard-dev-stage1\")].image","pause":"false"}]'
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: "2023-08-29T16:02:25Z"
    generation: 40
    labels:
      app: sci-scorecard-dev-stage1
      app.kubernetes.io/component: sci-scorecard-dev-stage1
      app.kubernetes.io/instance: sci-scorecard-dev-stage1
      app.kubernetes.io/name: sci-scorecard-dev-stage1
      app.kubernetes.io/part-of: sci-scorecard
    name: sci-scorecard-dev-stage1
    namespace: data-analytics
    resourceVersion: "4513269564"
    uid: 94eca875-dfb6-4dfc-844e-3ba3f091d5ab
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: sci-scorecard-dev-stage1
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: sci-scorecard-dev-stage1
          deploymentconfig: sci-scorecard-dev-stage1
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/data-analytics/sci-scorecard-dev-stage1@sha256:3b0f2fcdeca5587b3ff09f8c9bea9d530cd0e404234069a5e0154d2e848d6940
          imagePullPolicy: Always
          name: sci-scorecard-dev-stage1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/sftp
            name: volume-sftp-users
            readOnly: true
          - mountPath: /home/sci-scorecard/.ssh/keys/
            name: volume-9lwmg
            readOnly: true
          - mountPath: /home/sci-scorecard
            name: sci-scorecard-dev-vol01
            subPath: home/
          - mountPath: /etc/ssh/ssh_host_ed25519_key
            name: sci-scorecard-dev-vol01
            readOnly: true
            subPath: keys/ssh_host_ed25519_key
          - mountPath: /etc/ssh/ssh_host_rsa_key
            name: sci-scorecard-dev-vol01
            readOnly: true
            subPath: keys/ssh_host_rsa_key
          - mountPath: /etc/ssh/ssh_host_ed25519_key.pub
            name: sci-scorecard-dev-vol01
            readOnly: true
            subPath: keys/ssh_host_ed25519_key.pub
          - mountPath: /etc/ssh/ssh_host_rsa_key.pub
            name: sci-scorecard-dev-vol01
            readOnly: true
            subPath: keys/ssh_host_rsa_key.pub
          - mountPath: /data
            name: sci-scorecard-dev-vol01
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: useroot
        serviceAccountName: useroot
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: sci-scorecard-users
          name: volume-sftp-users
        - configMap:
            defaultMode: 420
            name: sci-scorecard-ssh-pub
          name: volume-9lwmg
        - name: sci-scorecard-dev-vol01
          persistentVolumeClaim:
            claimName: sci-scorecard-dev-vol01
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2023-08-29T16:02:25Z"
      lastUpdateTime: "2023-09-08T18:17:32Z"
      message: ReplicaSet "sci-scorecard-dev-stage1-57f794b57" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2024-12-07T16:09:17Z"
      lastUpdateTime: "2024-12-07T16:09:17Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 40
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      alpha.image.policy.openshift.io/resolve-names: '*'
      deployment.kubernetes.io/revision: "20"
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"sftp-debian:v1","namespace":"data-analytics"},"fieldPath":"spec.template.spec.containers[?(@.name==\"sftp-debian\")].image","pause":"false"}]'
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: "2021-06-15T12:47:43Z"
    generation: 62
    labels:
      app: sftp-data-analytics-app1
      app.kubernetes.io/component: sftp-data-analytics-app1
      app.kubernetes.io/instance: sftp-data-analytics-app1
      app.kubernetes.io/name: sftp-debian
      app.kubernetes.io/part-of: sftp-data-analytics-app1
      app.openshift.io/runtime: sftp-debian
      app.openshift.io/runtime-namespace: data-analytics
      app.openshift.io/runtime-version: v1
    name: sftp-data-analytics-app1
    namespace: data-analytics
    resourceVersion: "4513277823"
    uid: d4601561-267f-4fcd-a1a8-645a59189358
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: sftp-data-analytics-app1
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
        creationTimestamp: null
        labels:
          app: sftp-data-analytics-app1
          deploymentconfig: sftp-data-analytics-app1
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/data-analytics/sftp-debian@sha256:31ed9fa857f79fcd19bfe70d250bc8d760e91c1f605bb8ed969f9716237af970
          imagePullPolicy: IfNotPresent
          name: sftp-data-analytics-app1
          ports:
          - containerPort: 22
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/sftp
            name: volume-sftp-users
            readOnly: true
          - mountPath: /home/analytics/.ssh/keys/
            name: volume-9lwmg
            readOnly: true
          - mountPath: /home/analytics
            name: sftp-analytics-01
            subPath: home/
          - mountPath: /etc/ssh/ssh_host_ed25519_key
            name: sftp-analytics-01
            readOnly: true
            subPath: keys/ssh_host_ed25519_key
          - mountPath: /etc/ssh/ssh_host_rsa_key
            name: sftp-analytics-01
            readOnly: true
            subPath: keys/ssh_host_rsa_key
          - mountPath: /home/analytics/data
            name: nfspvcdataanalyticsdata01
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: useroot
        serviceAccountName: useroot
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: analytics-sftp-users
          name: volume-sftp-users
        - configMap:
            defaultMode: 420
            name: analytics-ssh-pub
          name: volume-9lwmg
        - name: sftp-analytics-01
          persistentVolumeClaim:
            claimName: sftp-analytics-01
        - name: nfspvcdataanalyticsdata01
          persistentVolumeClaim:
            claimName: nfspvcdataanalyticsdata01
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2021-06-30T18:40:26Z"
      lastUpdateTime: "2021-07-06T17:58:52Z"
      message: ReplicaSet "sftp-data-analytics-app1-5b4d555f46" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2024-12-07T16:11:48Z"
      lastUpdateTime: "2024-12-07T16:11:48Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 62
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      alpha.image.policy.openshift.io/resolve-names: '*'
      app.openshift.io/vcs-ref: sftp
      app.openshift.io/vcs-uri: https://bitbucket.org/kohler_prime/ia_unix
      deployment.kubernetes.io/revision: "9"
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"sftp-data-lake-app1:latest","namespace":"data-analytics"},"fieldPath":"spec.template.spec.containers[?(@.name==\"sftp-data-lake-app1\")].image","pause":"false"}]'
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: "2021-09-14T17:54:45Z"
    generation: 29
    labels:
      app: sftp-data-lake-app1
      app.kubernetes.io/component: sftp-data-lake-app1
      app.kubernetes.io/instance: sftp-data-lake-app1
      app.kubernetes.io/part-of: sftp-data-lake-app1
    name: sftp-data-lake-app1
    namespace: data-analytics
    resourceVersion: "4513277262"
    uid: 9ccd3d3e-1059-4ea3-9752-0b069d5ab755
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: sftp-data-lake-app1
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: sftp-data-lake-app1
          deploymentconfig: sftp-data-lake-app1
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/data-analytics/sftp-data-lake-app1@sha256:b6a22129dc132f7f68cfa342b23361f844dff65dc0232d1507253cfa2912ba85
          imagePullPolicy: Always
          name: sftp-data-lake-app1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/sftp
            name: volume-sftp-users
            readOnly: true
          - mountPath: /home/datalake/.ssh/keys/
            name: volume-9lwmg
            readOnly: true
          - mountPath: /home/datalake
            name: sftp-datalake-01
            subPath: home/
          - mountPath: /home/datalake/data
            name: sftp-datalake-data01
          - mountPath: /etc/ssh/ssh_host_ed25519_key
            name: sftp-datalake-01
            readOnly: true
            subPath: keys/ssh_host_ed25519_key
          - mountPath: /etc/ssh/ssh_host_rsa_key
            name: sftp-datalake-01
            readOnly: true
            subPath: keys/ssh_host_rsa_key
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: useroot
        serviceAccountName: useroot
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: datalake-sftp-users
          name: volume-sftp-users
        - configMap:
            defaultMode: 420
            name: datalake-ssh-pub
          name: volume-9lwmg
        - name: sftp-datalake-01
          persistentVolumeClaim:
            claimName: sftp-datalake-01
        - name: sftp-datalake-data01
          persistentVolumeClaim:
            claimName: sftp-datalake-data01
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2021-09-14T17:54:46Z"
      lastUpdateTime: "2021-09-14T18:51:44Z"
      message: ReplicaSet "sftp-data-lake-app1-85455cc56c" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2024-12-07T16:11:39Z"
      lastUpdateTime: "2024-12-07T16:11:39Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 29
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
