apiVersion: v1
items:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: "2021-06-15T12:47:43Z"
    labels:
      app: sftp-data-analytics-app1
      app.kubernetes.io/component: sftp-data-analytics-app1
      app.kubernetes.io/instance: sftp-data-analytics-app1
      app.kubernetes.io/part-of: sftp-data-analytics-app1
    name: sftp-data-analytics-app1
    namespace: data-analytics
    resourceVersion: "3949303675"
    uid: 2856029a-e6a9-461c-b948-d088898b1e14
  spec:
    host: sftp-data-analytics-app1-data-analytics.apps.ocp4.kohlerco.com
    port:
      targetPort: 22-tcp
    to:
      kind: Service
      name: sftp-data-analytics-app1
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: "2024-07-14T13:33:35Z"
        status: "True"
        type: Admitted
      host: sftp-data-analytics-app1-data-analytics.apps.ocp4.kohlerco.com
      routerCanonicalHostname: router-default.apps.ocp4.kohlerco.com
      routerName: default
      wildcardPolicy: None
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: "2021-09-14T17:54:46Z"
    labels:
      app: sftp-data-lake-app1
      app.kubernetes.io/component: sftp-data-lake-app1
      app.kubernetes.io/instance: sftp-data-lake-app1
      app.kubernetes.io/part-of: sftp-data-lake-app1
    name: sftp-data-lake-app1
    namespace: data-analytics
    resourceVersion: "3949302925"
    uid: 866c4894-8b1b-48a8-b64b-6dce1dbb3e08
  spec:
    host: sftp-data-lake-app1-data-analytics.apps.ocp4.kohlerco.com
    port:
      targetPort: 22-tcp
    to:
      kind: Service
      name: sftp-data-lake-app1
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: "2024-07-14T13:33:26Z"
        status: "True"
        type: Admitted
      host: sftp-data-lake-app1-data-analytics.apps.ocp4.kohlerco.com
      routerCanonicalHostname: router-default.apps.ocp4.kohlerco.com
      routerName: default
      wildcardPolicy: None
kind: List
metadata:
  resourceVersion: ""
