apiVersion: v1
items:
- apiVersion: v1
  imagePullSecrets:
  - name: builder-dockercfg-jkd5j
  - name: builder-quay-openshiftocp4
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2021-06-15T12:14:33Z"
    name: builder
    namespace: data-analytics
    resourceVersion: "2008514137"
    uid: a47451ff-6005-4253-ae44-e79dd668c4e9
  secrets:
  - name: builder-token-r9wb2
  - name: builder-dockercfg-jkd5j
  - name: builder-quay-openshiftocp4
- apiVersion: v1
  imagePullSecrets:
  - name: default-dockercfg-d7gsw
  - name: default-quay-openshiftocp4
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2021-06-15T12:14:33Z"
    name: default
    namespace: data-analytics
    resourceVersion: "2008514129"
    uid: b83780b3-dc9f-47d4-8a01-8747bf564256
  secrets:
  - name: default-token-b5mc7
  - name: default-dockercfg-d7gsw
  - name: default-quay-openshiftocp4
- apiVersion: v1
  imagePullSecrets:
  - name: deployer-dockercfg-x7ksn
  - name: deployer-quay-openshiftocp4
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2021-06-15T12:14:33Z"
    name: deployer
    namespace: data-analytics
    resourceVersion: "2008514131"
    uid: 78737146-05f0-4a0a-b627-7717bc5a2015
  secrets:
  - name: deployer-token-bhfsl
  - name: deployer-dockercfg-x7ksn
  - name: deployer-quay-openshiftocp4
- apiVersion: v1
  imagePullSecrets:
  - name: pipeline-dockercfg-s5n7s
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2022-12-01T01:07:13Z"
    name: pipeline
    namespace: data-analytics
    ownerReferences:
    - apiVersion: operator.tekton.dev/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: TektonInstallerSet
      name: rhosp-rbac-rtd8g
      uid: 96a8678d-2bd8-40db-b38a-3df25a2060bc
    resourceVersion: "1137374987"
    uid: 871191c7-a26b-41af-95d5-0b92a078b792
  secrets:
  - name: pipeline-token-87b79
  - name: pipeline-dockercfg-s5n7s
- apiVersion: v1
  imagePullSecrets:
  - name: useroot-dockercfg-jdd8g
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2021-06-15T12:17:55Z"
    name: useroot
    namespace: data-analytics
    resourceVersion: "355558437"
    uid: e7ed9d55-38b2-4ad4-8d95-de50eca59662
  secrets:
  - name: useroot-token-zrngl
  - name: useroot-dockercfg-jdd8g
kind: List
metadata:
  resourceVersion: ""
