apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: humanresourceapps-prd
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: humanresourceapps
    app.kubernetes.io/part-of: humanresource-platform
spec:
  project: default
  source:
    repoURL: https://github.com/rich-p-ai/kohler-apps.git
    targetRevision: HEAD
    path: humanresourceapps-migration/gitops/overlays/prd
  destination:
    server: https://kubernetes.default.svc
    namespace: humanresourceapps
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
