apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/backup-registry-hostname: docker-registry.default.svc:5000
    openshift.io/backup-server-version: "1.11"
    openshift.io/generated-by: OpenShiftWebConsole
    openshift.io/migration-registry: 172.30.105.8:5000
    openshift.io/restore-registry-hostname: image-registry.openshift-image-registry.svc:5000
    openshift.io/restore-server-version: "1.20"
  creationTimestamp: "2022-03-17T19:58:17Z"
  generation: 9
  labels:
    app: pm-procedures-prod
    migration.openshift.io/migrated-by-migmigration: 963fa791-d1d5-4d33-a8bd-f6bf82dc7685
    migration.openshift.io/migrated-by-migplan: beab174a-009f-4abf-9783-6ab7ab301523
    velero.io/backup-name: migration-555db-initial-km8f4
    velero.io/restore-name: migration-555db-final-wp57g
  name: pm-procedures-prod
  namespace: procurementapps
  resourceVersion: "4984597347"
  uid: 73828834-0300-4f2a-98ee-64aa18e71a13
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: pm-procedures-prod
    deploymentconfig: pm-procedures-prod
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      creationTimestamp: null
      labels:
        app: pm-procedures-prod
        deploymentconfig: pm-procedures-prod
    spec:
      containers:
      - env:
        - name: TZ
          value: America/Chicago
        envFrom:
        - configMapRef:
            name: pm-procedures-prod
        - secretRef:
            name: pm-procedures-certpass-prod
        - secretRef:
            name: pm-procedures-secrets-prod
        image: image-registry.openshift-image-registry.svc:5000/procurementapps/pm-procedures-webapp@sha256:20f5c9318ed9220eba37464f3b48394570865b43874d6c81800169c5eb35821f
        imagePullPolicy: Always
        name: pm-procedures-prod
        ports:
        - containerPort: 5001
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /i01/certs
          name: volume-cm7up
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: useroot
      serviceAccountName: useroot
      terminationGracePeriodSeconds: 30
      volumes:
      - name: volume-cm7up
        secret:
          defaultMode: 420
          secretName: pm-procedures-cert-prod2
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - pm-procedures-prod
      from:
        kind: ImageStreamTag
        name: pm-procedures-webapp:latest
        namespace: procurementapps
      lastTriggeredImage: image-registry.openshift-image-registry.svc:5000/procurementapps/pm-procedures-webapp@sha256:20f5c9318ed9220eba37464f3b48394570865b43874d6c81800169c5eb35821f
    type: ImageChange
  - type: ConfigChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-11-26T20:33:22Z"
    lastUpdateTime: "2022-11-26T20:33:29Z"
    message: replication controller "pm-procedures-prod-4" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-04-16T04:15:54Z"
    lastUpdateTime: "2025-04-16T04:15:54Z"
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  details:
    causes:
    - imageTrigger:
        from:
          kind: DockerImage
          name: image-registry.openshift-image-registry.svc:5000/procurementapps/pm-procedures-webapp@sha256:20f5c9318ed9220eba37464f3b48394570865b43874d6c81800169c5eb35821f
      type: ImageChange
    message: image change
  latestVersion: 4
  observedGeneration: 9
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
