apiVersion: v1
items:
- apiVersion: v1
  imagePullSecrets:
  - name: builder-dockercfg-l8qxc
  - name: builder-quay-openshiftocp4
  kind: ServiceAccount
  metadata:
    annotations:
      openshift.io/backup-registry-hostname: docker-registry.default.svc:5000
      openshift.io/backup-server-version: "1.11"
      openshift.io/migration-registry: 172.30.105.8:5000
      openshift.io/restore-registry-hostname: image-registry.openshift-image-registry.svc:5000
      openshift.io/restore-server-version: "1.20"
    creationTimestamp: "2022-03-17T19:56:04Z"
    labels:
      migration.openshift.io/migrated-by-migmigration: 963fa791-d1d5-4d33-a8bd-f6bf82dc7685
      migration.openshift.io/migrated-by-migplan: beab174a-009f-4abf-9783-6ab7ab301523
    name: builder
    namespace: procurementapps
    resourceVersion: "2008514500"
    uid: baef79ec-4c4e-4b9b-8921-f9c789cfede4
  secrets:
  - name: builder-token-dmw6q
  - name: builder-dockercfg-l8qxc
  - name: builder-quay-openshiftocp4
- apiVersion: v1
  imagePullSecrets:
  - name: default-dockercfg-cbsll
  - name: kohlercitregistry
  - name: default-quay-openshiftocp4
  kind: ServiceAccount
  metadata:
    annotations:
      openshift.io/backup-registry-hostname: docker-registry.default.svc:5000
      openshift.io/backup-server-version: "1.11"
      openshift.io/migration-registry: 172.30.105.8:5000
      openshift.io/restore-registry-hostname: image-registry.openshift-image-registry.svc:5000
      openshift.io/restore-server-version: "1.20"
    creationTimestamp: "2022-03-17T19:56:04Z"
    labels:
      migration.openshift.io/migrated-by-migmigration: 963fa791-d1d5-4d33-a8bd-f6bf82dc7685
      migration.openshift.io/migrated-by-migplan: beab174a-009f-4abf-9783-6ab7ab301523
    name: default
    namespace: procurementapps
    resourceVersion: "2008514503"
    uid: 3fc6139f-4296-4ceb-b0b5-24e53dfc98ee
  secrets:
  - name: default-token-s8ckr
  - name: default-dockercfg-cbsll
  - name: default-quay-openshiftocp4
- apiVersion: v1
  imagePullSecrets:
  - name: deployer-dockercfg-4h2mf
  - name: deployer-quay-openshiftocp4
  kind: ServiceAccount
  metadata:
    annotations:
      openshift.io/backup-registry-hostname: docker-registry.default.svc:5000
      openshift.io/backup-server-version: "1.11"
      openshift.io/migration-registry: 172.30.105.8:5000
      openshift.io/restore-registry-hostname: image-registry.openshift-image-registry.svc:5000
      openshift.io/restore-server-version: "1.20"
    creationTimestamp: "2022-03-17T19:56:04Z"
    labels:
      migration.openshift.io/migrated-by-migmigration: 963fa791-d1d5-4d33-a8bd-f6bf82dc7685
      migration.openshift.io/migrated-by-migplan: beab174a-009f-4abf-9783-6ab7ab301523
    name: deployer
    namespace: procurementapps
    resourceVersion: "2008514485"
    uid: 041898e7-c58d-432e-a3e8-39420d3ff4a8
  secrets:
  - name: deployer-token-z8hfv
  - name: deployer-dockercfg-4h2mf
  - name: deployer-quay-openshiftocp4
- apiVersion: v1
  imagePullSecrets:
  - name: pipeline-dockercfg-b8x49
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2022-12-01T01:07:25Z"
    name: pipeline
    namespace: procurementapps
    ownerReferences:
    - apiVersion: operator.tekton.dev/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: TektonInstallerSet
      name: rhosp-rbac-rtd8g
      uid: 96a8678d-2bd8-40db-b38a-3df25a2060bc
    resourceVersion: "1137376291"
    uid: 4b55a62f-deb6-46eb-9305-a022ac466c6d
  secrets:
  - name: pipeline-dockercfg-b8x49
  - name: pipeline-token-vcrkd
- apiVersion: v1
  imagePullSecrets:
  - name: kohlercitregistry
  - name: useroot-dockercfg-tvmxn
  kind: ServiceAccount
  metadata:
    annotations:
      openshift.io/backup-registry-hostname: docker-registry.default.svc:5000
      openshift.io/backup-server-version: "1.11"
      openshift.io/migration-registry: 172.30.105.8:5000
      openshift.io/restore-registry-hostname: image-registry.openshift-image-registry.svc:5000
      openshift.io/restore-server-version: "1.20"
    creationTimestamp: "2022-03-17T19:58:17Z"
    labels:
      migration.openshift.io/migrated-by-migmigration: 963fa791-d1d5-4d33-a8bd-f6bf82dc7685
      migration.openshift.io/migrated-by-migplan: beab174a-009f-4abf-9783-6ab7ab301523
      velero.io/backup-name: migration-555db-initial-km8f4
      velero.io/restore-name: migration-555db-final-wp57g
    name: useroot
    namespace: procurementapps
    resourceVersion: "677426627"
    uid: 6c8a15c0-a7bc-4fce-9564-b89c0a378a2e
  secrets:
  - name: useroot-dockercfg-tvmxn
  - name: useroot-token-pj954
kind: List
metadata:
  resourceVersion: ""
