apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: data-analytics

resources:
  - ../../base
  - storage.yaml
  - secrets.yaml
  - configmaps.yaml

patches:
  - target:
      group: ""
      version: v1
      kind: Namespace
      name: data-analytics
    patch: |-
      - op: add
        path: /metadata/labels/environment
        value: development
      - op: add
        path: /metadata/annotations/openshift.io~1display-name
        value: "Data Analytics - Development"

replicas:
  - name: "*"
    count: 1

labels:
  - pairs:
      environment: development
      tier: non-production
