apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: data-analytics
namePrefix: dev-

bases:
  - ../../base

patchesStrategicMerge:
  - namespace-patch.yaml

patchesJson6902:
  - target:
      group: ""
      version: v1
      kind: Namespace
      name: data-analytics
    patch: |-
      - op: add
        path: /metadata/labels/environment
        value: development
      - op: add
        path: /metadata/annotations/openshift.io~1display-name
        value: "Data Analytics - Development"

resources:
  - storage.yaml
  - secrets.yaml
  - configmaps.yaml

replicas:
  - name: "*"
    count: 1

images: []

commonLabels:
  environment: development
  tier: non-production
