apiVersion: v1
kind: ConfigMap
metadata:
  name: pm-procedures-prod
  namespace: procurementapps
  labels:
    app: pm-procedures-prod
    component: pm-procedures
    environment: production
data:
  DB_TYPE: sqlserver
  DB_SERVER: sqlprdtxsql01.kohlerco.com
  DB_DATABASE: procurement_procedures
  DB_DRIVER: ODBC Driver 17 for SQL Server
  SSL_CERT: /opt/app-root/src/ssl/tls.crt
  SSL_KEY: /opt/app-root/src/ssl/tls.key
  NODE_ENV: production
  PORT: "5001"
  TZ: America/Chicago
  ASPNETCORE_ENVIRONMENT: Production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pm-procedures-test
  namespace: procurementapps
  labels:
    app: pm-procedures-test
    component: pm-procedures
    environment: test
data:
  DB_TYPE: sqlserver
  DB_SERVER: sqldevtxsql01.kohlerco.com
  DB_DATABASE: procurement_procedures_test
  DB_DRIVER: ODBC Driver 17 for SQL Server
  SSL_CERT: /opt/app-root/src/ssl/tls.crt
  SSL_KEY: /opt/app-root/src/ssl/tls.key
  NODE_ENV: test
  PORT: "5001"
  TZ: America/Chicago
  ASPNETCORE_ENVIRONMENT: Development
