apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: pm-procedures-prod
  namespace: procurementapps
  labels:
    app: pm-procedures-prod
    component: pm-procedures
    environment: production
spec:
  host: pm-procedures-prod.apps.ocp-prd.kohlerco.com
  port:
    targetPort: 5001-tcp
  tls:
    termination: passthrough
  to:
    kind: Service
    name: pm-procedures-prod
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: pm-procedures-test
  namespace: procurementapps
  labels:
    app: pm-procedures-test
    component: pm-procedures
    environment: test
spec:
  host: pm-procedures-test.apps.ocp-prd.kohlerco.com
  port:
    targetPort: 5001-tcp
  tls:
    termination: passthrough
  to:
    kind: Service
    name: pm-procedures-test
    weight: 100
  wildcardPolicy: None
