apiVersion: v1
kind: Secret
metadata:
  name: pm-procedures-cert-prod2
  namespace: procurementapps
  labels:
    app: pm-procedures-prod
    component: pm-procedures
    environment: production
type: Opaque
data:
  pm-procedures-prod.apps.oc.kohlerco.com.official.p12: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
---
apiVersion: v1
kind: Secret
metadata:
  name: pm-procedures-cert-test2
  namespace: procurementapps
  labels:
    app: pm-procedures-test
    component: pm-procedures
    environment: test
type: Opaque
data:
  pm-procedures-test.apps.ocp4.kohlerco.com.official.p12: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
---
apiVersion: v1
kind: Secret
metadata:
  name: pm-procedures-certpass-prod
  namespace: procurementapps
  labels:
    app: pm-procedures-prod
    component: pm-procedures
    environment: production
type: Opaque
data:
  certificate-password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: pm-procedures-certpass-test
  namespace: procurementapps
  labels:
    app: pm-procedures-test
    component: pm-procedures
    environment: test
type: Opaque
data:
  certificate-password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: pm-procedures-secrets-prod
  namespace: procurementapps
  labels:
    app: pm-procedures-prod
    component: pm-procedures
    environment: production
type: Opaque
data:
  DATABASE_CONNECTION: cG9zdGdyZXNxbDovL2RhdGFiYXNlLmV4YW1wbGUuY29tOjU0MzIvZGI=
  API_KEY: YXBpa2V5MTIz
  OTHER_SECRET: c2VjcmV0dmFsdWU=
---
apiVersion: v1
kind: Secret
metadata:
  name: pm-procedures-secrets-test
  namespace: procurementapps
  labels:
    app: pm-procedures-test
    component: pm-procedures
    environment: test
type: Opaque
data:
  DATABASE_CONNECTION: cG9zdGdyZXNxbDovL3Rlc3QtZGF0YWJhc2UuZXhhbXBsZS5jb206NTQzMi9kYg==
  API_KEY: dGVzdGFwaWtleQ==
  OTHER_SECRET: dGVzdHNlY3JldA==
