apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oraclecpq-prd
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/rich-p-ai/kohler-apps.git
    targetRevision: main
    path: oraclecpq-migration/gitops/overlays/prd
  destination:
    server: https://kubernetes.default.svc
    namespace: oraclecpq
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
